<?php

/**
 * @file
 * Contains zoular.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function zoular_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the zoular module.
    case 'help.page.zoular':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Zoular Project Module') . '</p>';
      return $output;

    default:
  }
}
